

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca_testing.csv"
  TARGET_VAR: "Credit_Score"
  n_estimators: 505
  max_depth: 37
  RANDOM_STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
      
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 
      

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow PyDrive2 google-auth google-auth-oauthlib google-auth-httplib2
        
      - name: Upload artifacts to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}    # JSON isi credential
          # Opsional: folder ID bisa disimpan di secrets/variable
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          echo "Mulai upload folder mlruns ke Google Drive..."
          python MLproject/upload_to_drive.py "./mlruns" "$GDRIVE_FOLDER_ID"
            
      # - name: Set up Git LFS
      #   run: |
      #     git config --global user.name ${{ secrets.username }}
      #     git config --global user.email ${{ secrets.email }}
      #     git lfs install
      #     git lfs track "mlruns/**"
      #     git add .gitattributes
      #     git commit -m "Track large files in mlruns with Git LFS" || true
      #     git push origin main
          
      # # Save models to GitHub Repository
      # - name: Save mlruns to repo
      #   run: |
      #     git config --global user.name ${{ secrets.username }}
      #     git config --global user.email ${{ secrets.email }}
      #     git add -f mlruns/
      #     git commit -m "Save mlruns from CI run" || true
      #     git push origin main
